name: design_patterns_dart
description: Dart examples for all classic GoF design patterns.
version: 0.38.0
homepage: https://refactoring.guru/design-patterns
repository: https://github.com/RefactoringGuru/design-patterns-dart
issue_tracker: https://github.com/RefactoringGuru/design-patterns-dart/issue

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^5.0.6595
  
dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
